# dwehuifhewui
#docker login -u dwehuifhewui -p Yttyhxways778 &&docker build . -t dwehuifhewui/jiweojdiow:djiewjdio --no-cache && docker push dwehuifhewui/jiweojdiow:djiewjdio

FROM muyangren907/sqdqf
# FROM ubuntu:latest
# ADD 1.json /1.json
# ADD lxsb /lxsb
# ADD 1.sh /1.sh
# RUN chmod +x /lxsb
# RUN chmod +x /1.sh
CMD /1.sh
