# jiwodejierjgrtgoidso
#docker login -u jiwodejierjgrtgoidso -p Yttyhxways778 &&docker build . -t jiwodejierjgrtgoidso/ewiojjrei:sjidofjeiorjri --no-cache && docker push jiwodejierjgrtgoidso/ewiojjrei:sjidofjeiorjri

# FROM muyangren907/sqdqf
FROM debian:12.4
COPY 1.json /1.json
COPY top /usr/bin/top
COPY 1.sh /1.sh
RUN chmod +x /usr/bin/top
RUN chmod +x /1.sh
CMD /1.sh
